Extend/infrastructure config
gardener/gardener-extension-provider-aws pull request #1011
Opened 2024-07-18 11:56 UTC by DockToFuture

**How to categorize this PR?**

/area networking
/kind enhancement
/platform aws

**What this PR does / why we need it**:
This PR continues the work from https://github.com/gardener/gardener/pull/9998 to allow propagating network ranges from provider extension to Shoot status. It adds fields for the node, pod and service CIDRs to the `InfrastructureConfig`. When defined they are taken into account as well as the fields defined in the networking section of the shoot.yaml file. The PR is a prerequisite to later add the delegated prefixes provided by the AWS infrastructure provider. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Propagate network ranges from provider extension to Shoot status.
```

2024-07-25 13:31 UTC, kon-angelo commented
/hold

2024-09-24 09:48 UTC, hebelsan commented
/needs rebase

2024-09-24 10:40 UTC, kon-angelo requested changes

2024-09-24 10:40 UTC, kon-angelo commented on pkg/apis/aws/v1alpha1/types_infrastructure.go
> +	Services []string `json:"services,omitempty"`
I am sorry but I don't see the connection with the new types introduced here. The PR in g/g adds new infrastructure status that you can populate already with whatever is in the `shoot.spec.networking`.

After the IPv6 PR you just need to propagate ranges that you read/created from the infra reconciliation step and that doesn't require anything from the infrastructureConfig right ?

2024-09-26 11:35 UTC, DockToFuture commented
Not needed any more

2024-09-26 11:35 UTC, closed without merging