[GEP-26] Support shoots using CredentialsBinding
gardener/gardener-extension-provider-aws pull request #1047
Opened 2024-09-04 08:01 UTC by dimityrmirchev

**How to categorize this PR?**

/area security ipcei
/kind enhancement
/platform aws
/label ipcei/workload-identity

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9586

**Special notes for your reviewer**:

**Release note**:

```feature user
The admission webhook now validates `CredentialsBinding`s.
```

2024-09-04 08:01 UTC, dimityrmirchev commented
cc @vpnachev

2024-09-05 13:11 UTC, vpnachev requested changes
Some nits and one issue that I found, the admission controller fails to start up because the scheme is missing entry for the CredentialsBinding resource. 

You have to add 

```go
github.com/gardener/gardener/pkg/apis/security/install.Install(mgr.GetScheme())
```

somewhere here https://github.com/gardener/gardener-extension-provider-aws/blob/5a0ca81b53918509d147b0e0c141480fdc4266a3/cmd/gardener-extension-admission-aws/app/app.go#L120

2024-09-05 13:16 UTC, dimityrmirchev commented on pkg/admission/validator/credentialsbinding.go
> +		// The relevant fields of the credentials binding are immutable so we can exit early on update
Yes, I think that we can hold off until that PR is merged.

2024-09-05 13:17 UTC, dimityrmirchev commented
Thanks for reviewing, I will also address your feedback in the other PRs that I opened for other provider extensions. Meanwhile I will move their status to draft until this one is finalized.

2024-09-11 18:31 UTC, vpnachev commented
/lgtm

2024-09-12 12:49 UTC, dimityrmirchev commented
/label reviewed/ok-to-test

2024-09-13 10:49 UTC, vpnachev commented
/lgtm

2024-09-17 08:49 UTC, kon-angelo approved these changes
/lgtm

2024-09-17 08:50 UTC, merged