Introduce `InfrastructureConfigFromCluster` and use it instead of api call
gardener/gardener-extension-provider-aws pull request #1068
Opened 2024-09-24 08:25 UTC by Kostov6

**How to categorize this PR?**

/area bug
/kind enhancement
/platform aws

**What this PR does / why we need it**:
This PR introduces `InfrastructureConfigFromCluster` that extracts the `api.InfrastructureConfig` from a cluster resource and uses it in `pkg/webhook/controlplane/ensurer.go` instead of a api call to get the infra resource.

**Which issue(s) this PR fixes**:
This fixes a issue where cluster force deletion may fail

**Special notes for your reviewer**:

**Release note**:

```other developer
NONE
```

2024-09-26 10:19 UTC, ialidzhikov requested changes

2024-09-26 10:19 UTC, ialidzhikov commented on pkg/apis/aws/helper/scheme.go
> +		if _, _, err := decoder.Decode(cluster.Shoot.Spec.Provider.InfrastructureConfig.Raw, nil, infra); err != nil {
How does this work and did you test this at all? It should not be possible to decode `shoot.spec.provider.infrastructureConfig` to `*extensionsv1alpha1.Infrastructure`. `shoot.spec.provider.infrastructureConfig` should be decoded to `*api.InfrastructureConfig` instead.

2024-09-27 08:29 UTC, ialidzhikov submitted a review, later dismissed
/lgtm

2024-10-09 14:39 UTC, hebelsan commented
/lgtm

2024-10-15 12:26 UTC, kon-angelo approved these changes
/lgtm

2024-10-15 12:28 UTC, merged

2024-10-17 11:19 UTC, ialidzhikov commented
@Kostov6 when you rebased the PR, you reverted the fixes for https://github.com/gardener/gardener-extension-provider-aws/pull/1068#discussion_r1776785054 that I pushed 🙈 . See https://github.com/gardener/gardener-extension-provider-aws/pull/1086