SC Gardener aws-ebs-csi-driver image update
gardener/gardener-extension-provider-aws pull request #1080
Opened 2024-10-07 18:19 UTC by scs-gardener-team-gitlab

**How to categorize this PR?**

/area storage
/area control-plane
/area delivery
/kind bug
/platform aws

**What this PR does / why we need it**:
SC Gardener landscapes require the aws csi-driver to run in legacyXFS mode. To do this the parameter needs to be configurable inside of the values.yaml file as well as added to the daemonset if aforementioned parameter is set to `True`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Test manually. Paused the corresponding managed resource object, edited the csi-driver pod and its image for one of our cluster to use the `1.35.0` version. Then, edited the pod spec to include the extra legacyXFS patameter. The pod is running fine with no issues in legacyXFS mode.

**Release note**:

```other operator
The following images are updated:
registry.k8s.io/provider-aws/aws-ebs-csi-driver: v1.29.0 -> v1.35.0
```

2024-10-07 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener-extension-provider-aws?pullRequest=1080) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener-extension-provider-aws?pullRequest=1080) before we can accept your contribution.<br/><hr/>**i547123** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener-extension-provider-aws?pullRequest=1080) it.</sub>

2024-10-07 18:39 UTC, scs-gardener-team-gitlab commented
Additional Links:
- PR on the AWS EBS CSI driver repo: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2121
- Github issue that brought it to AWS's attention: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/2110

2024-10-08 06:22 UTC, kon-angelo commented
The PR does not really enable the XFS option though does it ? From a user's perspective, how can he enable the new Helm chart option if it's not exposed via the shoot spec (e.g. controlplaneConfig)

2024-10-08 06:23 UTC, kon-angelo requested changes
See comment above

2024-10-09 13:20 UTC, hebelsan commented
lgtm. Let's merge this [PR](https://github.com/gardener/gardener-extension-provider-aws/pull/1072/files) first though.

2024-10-16 16:14 UTC, aabond commented
Hi @kon-angelo and @hebelsan ,

Are we ready to proceed with merging this PR?

2024-10-16 17:30 UTC, kon-angelo requested changes

2024-10-16 17:30 UTC, kon-angelo commented on pkg/controller/controlplane/valuesprovider.go
> +
With the code as it is, you would overwrite the value of `VolumeAttachLimit` in the `driver` key of the map. You should only create the map if it's not there.

2024-10-17 14:44 UTC, kon-angelo requested changes

2024-10-17 14:44 UTC, kon-angelo commented on charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
> +        - --legacyXFS={{ .Values.driver.legacyXFS }}
Also this flag is not even correct. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/7fd319a43ee6fe339517051226c506304d3f5f94/pkg/driver/options.go#L120 is the proper format.

2024-10-17 14:59 UTC, AndreasBurger approved these changes

2024-10-17 22:18 UTC, hebelsan commented on docs/usage/usage.md
> +A workaround was added that enables the use of a "legacy XFS" mode that introduces a backwards compatible volume formating for the older kernels. You can enable this option for your shoot by using by
```suggestion
A workaround was added that enables the use of a "legacy XFS" mode that introduces a backwards compatible volume formating for the older kernels. You can enable this option for your shoot by annotating it with `aws.provider.extensions.gardener.cloud/legacy-xfs=true`.
```

2024-10-18 07:38 UTC, AndreasBurger approved these changes

2024-10-18 08:03 UTC, merged