[WIP] Adjustments for deploying extension on Garden runtime cluster by gardener-operator
gardener/gardener-extension-provider-aws pull request #1100
Opened 2024-10-25 12:34 UTC by MartinWeindel

**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform aws

**What this PR does / why we need it**:
To deploy the provider extension into the Garden runtime cluster by gardener-operator with extension class `garden`, some adjustments are needed in the charts. Some missing glue code have been added.
Additionally the g/g dependencies has been updated for the upcoming v1.107.0 release.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This is work in progress and will probably see some refactorings especially regarding the new chart values.
part of https://github.com/gardener/gardener/issues/9635

**Release note**:

```feature operator
Adjustments for deploying extension on Garden runtime cluster by gardener-operator
```

/cc @timuthy @oliver-goetz

2024-11-14 12:36 UTC, AndreasBurger reviewed
lgtm

2024-11-18 17:08 UTC, oliver-goetz requested changes
I just noticed in my own PR that with these changes the helm charts are not correct anymore. There are a couple of references to images/image tags which overwrite `global.image.`tags in the pipeline definition ([ref](https://github.com/gardener/gardener-extension-provider-aws/blob/7f20607254dd3c64681516df1de919a440a694c3/.ci/pipeline_definitions#L13-L30)).

2024-11-19 13:56 UTC, MartinWeindel commented
> I just noticed in my own PR that with these changes the helm charts are not correct anymore. There are a couple of references to images/image tags which overwrite `global.image.`tags in the pipeline definition ([ref](https://github.com/gardener/gardener-extension-provider-aws/blob/7f20607254dd3c64681516df1de919a440a694c3/.ci/pipeline_definitions#L13-L30)).
> 
> A fix could look like [this](https://github.com/gardener/gardener-extension-provider-gcp/pull/905/commits/f600bf1c6ec0bd840c8f1340fe238eac81d6b1c6).

Thanks! Fixed now.

2024-11-19 19:09 UTC, oliver-goetz submitted a review, later dismissed
thanks 😄

2024-11-20 08:28 UTC, timuthy requested changes
Thanks for the changes, very nice 👏

2024-11-20 08:28 UTC, timuthy commented on charts/gardener-extension-provider-aws/templates/deployment.yaml
> +        - --disable-controllers=backupentry,bastion,controlplane,infrastructure,worker,healthcheck
```suggestion
        - --controllers=backupbucket,dnsrecord
```

Better use positive list?

2024-11-20 10:34 UTC, MartinWeindel commented on charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
> +  - create
Good question. I've just tested it without, and it works fine. Not sure why it was added.
Thanks for the catch.

2024-11-20 10:35 UTC, MartinWeindel commented on charts/gardener-extension-admission-aws/charts/application/templates/rbac.yaml
> +  - update
Lease is on the runtime cluster. Thanks for catching. Maybe introduced during some inconsisten intermediate deployment.

2024-11-20 16:03 UTC, timuthy approved these changes
/lgtm

2024-11-20 16:04 UTC, merged