Allowing IOPS for all volume types, removing IOPS range validation
gardener/gardener-extension-provider-aws pull request #561
Opened 2022-06-16 04:49 UTC by rishabh-11

**How to categorize this PR?**

/area storage
/kind bug
/platform aws

**What this PR does / why we need it**:
This PR allows setting IOPS for any volume type and moves the validation to the AWS side. 
**Which issue(s) this PR fixes**:
Fixes #488 

**Special notes for your reviewer**:
Testing it on dev landscape is left
**Release note**:

```bugfix user
Users can now set IOPS for a GP3 volume type. Validation of IOPS (i.e. whether it is allowed and is in the specified range for a volume type) is done on the AWS side, so feedback will arrive once the volume is created. 
```

2022-06-17 10:30 UTC, himanshu-kun requested changes
looks good otherwise

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/types_worker.go
> +	// Constraint: Constraint: IOPS should be a positive value.
```suggestion
	// Constraint: IOPS should be a positive value.
```

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker.go
> +		allErrs = append(allErrs, field.Forbidden(iopsPath, "iops must be a non negative value"))
```suggestion
	if volume != nil && volume.IOPS != nil && *volume.IOPS <= 0 {
		allErrs = append(allErrs, field.Forbidden(iopsPath, "iops must be a positive value"))
```

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker.go
> +		return allErrs
This change is not needed

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker_test.go
> +		It("should enforce that the IOPS is non negative", func() {
```suggestion
		It("should enforce that the IOPS is positive", func() {
```

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker.go
> -		}
keep this validation

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker_test.go
> +			worker.Volume.IOPS = nil
add the case of providing gp2iops also passing , but comment that it would fail later by AWS as currently gp2 doesn't support iops.

2022-06-17 10:30 UTC, himanshu-kun commented on pkg/apis/aws/validation/worker_test.go
> -			Expect(errorList).To(ConsistOf(
keep this testcase

2022-06-23 15:13 UTC, himanshu-kun approved these changes
/lgtm

2022-06-23 15:14 UTC, himanshu-kun commented
/invite @unmarshall @dkistner

2022-06-24 04:02 UTC, unmarshall approved these changes
/lgtm

2022-06-24 07:05 UTC, dkistner approved these changes
/lgtm

2022-06-24 07:06 UTC, merged