Block public access to S3 bucket as per standard practices
gardener/gardener-extension-provider-aws pull request #738
Opened 2023-04-19 10:27 UTC by shreyas-s-rao

**How to categorize this PR?**

/area backup
/area security
/area compliance
/kind task
/platform aws

**What this PR does / why we need it**:
This PR configures the newly created S3 buckets to be blocked from public access as per standard practices. This is achieved by putting a public-access-block on the created bucket, as per [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/put-public-access-block.html).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @vlerenc 

**Release note**:

```other operator
Block public access for newly created S3 buckets.
```

2023-04-19 10:56 UTC, abdasgupta requested changes
I think we need to add bucket policy here

2023-04-19 10:56 UTC, abdasgupta commented on pkg/aws/client/client.go
> +
I think we should add bucket policy here. I received some alert for not having proper bucket policies. Example bucket policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "RestrictToTLSRequestsOnly",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::9eeccd1a-d2d1-499b-977c-0d346f9d3b79/*",
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                },
                "NumericLessThan": {
                    "s3:TlsVersion": "1.2"
                }
            }
        }
    ]
}
```
More info: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-language-overview.html

2023-04-21 06:43 UTC, shreyas-s-rao commented
@abdasgupta thanks, I have addressed your comment now. PTAL

2023-05-03 03:35 UTC, shreyas-s-rao commented
/ping @gardener/gardener-extension-provider-aws-maintainers

2023-05-03 07:36 UTC, kon-angelo approved these changes
/lgtm

2023-05-03 07:37 UTC, merged