Remove dependency to specific calico and cilium versions.
gardener/gardener-extension-provider-aws pull request #807
Opened 2023-09-27 11:30 UTC by axel7born

**How to categorize this PR?**

/area networking
/kind technical-debt
/platform aws

**What this PR does / why we need it**:
This PR removes the dependency to specific calico and cilium versions.
After each api change of a network extension, the new version needed to be vendored here and a new release has to be made in order to pass admission.
By parsing the network into a general map instead into an object of type `NetworkConfig` we can get rid of this dependency. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy developer
Remove dependency to specific calico and cilium versions.
```

2023-09-27 12:16 UTC, ScheererJ commented
/cc @afritzler

2023-09-27 12:34 UTC, ScheererJ requested changes
Thanks for the nice improvement. It will certainly make the delivery process more flexible.

2023-09-27 12:34 UTC, ScheererJ commented on pkg/admission/mutator/shoot.go
>  	if shoot.Spec.Networking != nil && shoot.Spec.Networking.Type != nil {
Do we need to check for `shoot.Spec.Networking.Type != nil`? It is not strictly wrong, but probably not required anymore.

2023-09-27 12:34 UTC, ScheererJ commented on pkg/admission/mutator/shoot.go
> -			overlay := &ciliumv1alpha1.Overlay{Enabled: false}
Do we want to use constants for `overlay` and `enabled` to prevent typos? These strings are used multiple times here.

2023-09-27 15:07 UTC, ScheererJ approved these changes
/lgtm

2023-09-28 08:28 UTC, DockToFuture approved these changes
/lgtm

2023-09-28 08:43 UTC, shafeeqes commented
You could also remove the `replace k8s.io/client-go => k8s.io/client-go v0.26.4` redirective, then we don't need https://github.com/gardener/gardener-extension-provider-aws/pull/800

2023-09-28 09:03 UTC, kon-angelo commented on pkg/admission/mutator/shoot.go
> +		network = &runtime.RawExtension{
maybe you can return here directly - skipping unmarshal ?

2023-09-28 11:21 UTC, kon-angelo approved these changes
/lgtm

2023-09-28 11:21 UTC, merged